version: "3.7"

services:

  vertical_nginx:
    image: nginx:alpine
    container_name: vertical_nginx
    ports:
      - 80:80
    depends_on:
      - vertical_api
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vertical_network

  vertical_api:
    build: ..
    image: vertical:latest
    container_name: vertical_api
    ports:
      - 8080:8080
    environment:
      - AUTH_DB_URL=postgresql://vertical:vertical@vertical_db:5432/vertical
      - HUNTER_DB_URL=postgresql://hunter:hunter@hunter_db:5432/hunter
    depends_on:
      - vertical_db
      - vertical_migrations
      - hunter_db
    networks:
      - vertical_network

  vertical_migrations:
    image: vertical:latest
    container_name: vertical_migrations
    environment:
      - AUTH_DB_URL=postgresql://vertical:vertical@vertical_db:5432/vertical
    depends_on:
      - vertical_db
    command: sh -c "sleep 2 && alembic upgrade head"
    networks:
      - vertical_network

  vertical_db:
    image: postgres:11-alpine
    container_name: vertical_db
    ports:
      - 8081:5432
    environment:
      - POSTGRES_USER=vertical
      - POSTGRES_PASSWORD=vertical
      - POSTGRES_DB=vertical
    networks:
      - vertical_network

  hunter_db:
    image: postgres:11-alpine
    container_name: hunter_db
    ports:
      - 8082:5432
    environment:
      - POSTGRES_USER=hunter
      - POSTGRES_PASSWORD=hunter
      - POSTGRES_DB=hunter
    volumes:
      - ./hunter_migrations:/docker-entrypoint-initdb.d/
    networks:
      - vertical_network

networks:
  vertical_network:
    name: vertical_network
